### ISSUE TITLE
`reponame` stands for repository name and package name, but they may not be the same

### ISSUE THREAD

**Issue by ceball** [ioam/autover#38]
Not sure if I'm misunderstanding, but in fns like `get_setup_version(reponame)`, is `reponame` the name of the repository, the package, or both? It kind of looks like it might be both, though I'm not sure...but if so, that could be a problem if the two things aren't the same (e.g. repository called `EarthSim`, package called `earthsim`...).

**Comment by jbednar** [comment]
In general I would argue that people should use at least different case between the repository and the package name, as it makes debugging path issues vastly easier.  E.g. at some point a Travis log had output like `.../pyviz/piviz/pyviz/...`,  and we couldn't tell whether there was a bogus extra directory in the path because the organization, the repo, and the module all have the same name.  So yes, we do need to distinguish those.

**Comment by jlstevens** [comment]
> Not sure if I'm misunderstanding, but in fns like get_setup_version(reponame), is reponame the name of the repository, the package, or both?

Currently it means both. This works for most of our projects ``param``, ``holoviews``, ``geoviews``, ``datashader`` etc but you are right it won't work if you don't match the reponame with the package name. I would argue you *should* match them up but there will be cases where it won't be true and autover would need to be generalized for such cases.

It shouldn't be hard to do but it is a pain regardless.

**Comment by jbednar** [comment]
I don't see any argument for matching repo and package names; seems like that always sets up an ambiguity and makes it hard for people to get the right bit on their PYTHON_PATH.  I assume you do have such an argument, though?

**Comment by jlstevens** [comment]
> I don't see any argument for matching repo and package names; seems like that always sets up an ambiguity and makes it hard for people to get the right bit on their PYTHON_PATH.

What do you mean?

What I'm thinking is for python, if I see a GitHub project called ``holoviews`` I expect to use ``import holoviews``. This is true for the majority of our projects.

I have a vague memory that long ago when we first made the holoviews repo, we considered naming the repo ``HoloViews`` while still importing ``holoviews``. We decided against that (rightly imho) as that adds unnecessary confusion.

**Comment by jbednar** [comment]
The ambiguity is just that if you see a directory named "holoviews", you have no idea whether that's the Python module, the repo, or in some cases (as for Bokeh) the organization.  So having them all have the same name may be good for knowing what to fill in somewhere, but for precisely the same reason it's bad for being able to distinguish them.  E.g. in instructions that we tell users, it's very hard to tell them what directory to go into, as they are all named the same if they have a github checkout.  Anyway, I think my position here is clear, and I understand what you're saying as well, so I think we have to leave it at that.

**Comment by jlstevens** [comment]
Do we have any other examples of projects that we want to use ``autover`` that has this issue? ``EarthSim`` seems to be the only one I can think of right now...

**Comment by jbednar** [comment]
There are various others that use mixed case in our organization's private repos.

**Comment by jlstevens** [comment]
> There are various others that use mixed case in our organization's private repos.

Right. But any we want to use autover with in the short term?

**Comment by jbednar** [comment]
Isn't EarthSim a sufficient reason?

**Comment by jlstevens** [comment]
> Isn't EarthSim a sufficient reason?

It is definitely sufficient, the question is about priority. We have a lot of packages that need to be updated with the new versioning/building infrastructure and EarthSim is only one of them. I don't think this issue holds up any of *that* work until we get round to needing autover in EarthSim.

Right now EarthSim doesn't currently have a proper [setup.py](https://github.com/pyviz/EarthSim/blob/master/setup.py) that declares its dependencies properly. For instance, EarthSim does seem to depend on [param](https://github.com/pyviz/EarthSim/blob/master/earthsim/analysis.py#L7) which means it should probably get autover from param, just like our other projects using this approach.

Unless using autover in EarthSim has a higher priority than I currently realize, I think this issue can be fixed by making sure autover is updated for the next *regular* param release. As we expect param to be more active in the coming months, I don't think this issue should *force* a new param release. Instead, this just needs to be addressed in time so that it can be used with whenever new param improvements/features are made available.

Otherwise, if versioning EarthSim is more pressing than that, I can fix this issue now, cut an autover release and then bundle it in EarthSim. Later, Earthsim can use the param version once that is available. That said, this does seem like more work than is strictly necessary right now.

Lastly, if the EarthSim repo were renamed to ``earthsim``, there would be no issue and that would be consistent with *all* our other projects on pyviz. Although I would *personally* prefer this route, I do agree that decoupling reponame from the package name is a necessary fix for autover (even if I personally prefer projects that don't require this distinction).

**Comment by jbednar** [comment]
I don't think there is any reason to postpone fixing this problem. Whether EarthSim needs a release soon or not, it is entirely incorrect for autover to be assuming that the reponame and the module name are the same in general, so we may as well fix it while it's fresh in mind.  So I propose immediately fixing autover now, to avoid this incorrect assumption.  If the fix does not change the API needed for most of our other projects, then there will then be no particular rush for eventually:

- releasing autover
- updating autover in param
- updating EarthSim to use autover

But we'll be able to do it whenever we need to. EarthSim is just an example of why this change is needed; the timescales involved do not need to be linked, and we should fix the problem regardless.

**Comment by jlstevens** [comment]
> ... so we may as well fix it while it's fresh in mind

Sure. That is one reason to do it now.

> ... If the fix does not change the API needed for most of our other projects, then there will then be no particular rush

I suppose that can be arranged if the default behavior is to assume they are the same (current behavior) but add an optional argument to specify the different package name if required.

**Comment by jlstevens** [comment]
> ... then there will then be no particular rush for eventually:
>
> * releasing autover
> * updating autover in param
> * updating EarthSim to use autover

That is also fine, it just means EarthSim will need to wait for an updated autover to be available from param.

**Comment by ceball** [comment]
Fixed in #39
