### ISSUE TITLE
What kind of dependency will my project have on autover?

### ISSUE THREAD

**Issue by ceball** [ioam/autover#7]
If I want to use autover in all the ways described in #2, will I be adding autover as an external dependency of my package? If so, will that be an external dependency when my project is imported, or will it only be required when my project is packaged? If autover's not meant to be an external dependency, how should I include it in my project?

**Comment by ceball** [comment]
To clarify, there's potentially: 
  1. "developer run time" dependency for someone using the git source
  2. "build time" dependency when creating a package
  3. "user run time" dependency for a user importing a distributed package

It would be great if 3 were not required, although this is probably an "optional, nice to have" feature. I'm not personally concerned about 1 and 2.

**Comment by jlstevens** [comment]
If you choose to inline the file with ``Version``, there is no dependency in any of those cases. This is a good idea for small projects (e.g param) and it is still lighter than versioneer (one, much shorter file needed instead of two).

In all other cases, it is a dependency although it can fall back to the version specified in the ``.version`` file (which might not be the very latest) when building. This means autover isn't *strictly* necessary in this situation but it is recommended if you want to guarantee having the very latest version strings.

**Comment by jlstevens** [comment]
Autover is simply a build time dependency for packaging (conda/ pypi) and is not required by users for releases. It is needed by users who want to get the latest version information out of their git repo. The cases are:

1. Not required for by users for releases.
2. Bundled (i.e the file is included in the project). Satisfies both build and run time dependencies.
3. Autover is available as a package (to satisfy the build time dependency).
4. Autover available via param (which will simplify things a lot for most pyviz projects)
5. Fetched automatically (only needed for the pip+git case)

Other than documenting this (#8) we now know how autover works as a build and runtime dependency. Note that versioneer uses bundling (option 2) which autover can do as well, in which case it will always be available. Closing.
